// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app_layout from "./routes/(app)/_layout.tsx";
import * as $_app_middleware from "./routes/(app)/_middleware.tsx";
import * as $_app_carrito from "./routes/(app)/carrito.tsx";
import * as $_app_home from "./routes/(app)/home.tsx";
import * as $_app_spells_index_ from "./routes/(app)/spells/[index].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $carrito_boton from "./islands/carrito_boton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $_app_layout,
    "./routes/(app)/_middleware.tsx": $_app_middleware,
    "./routes/(app)/carrito.tsx": $_app_carrito,
    "./routes/(app)/home.tsx": $_app_home,
    "./routes/(app)/spells/[index].tsx": $_app_spells_index_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Form.tsx": $Form,
    "./islands/Header.tsx": $Header,
    "./islands/carrito_boton.tsx": $carrito_boton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
